### ISSUE TITLE
Scaffold React app

### ISSUE THREAD

**Issue by kadamwhite** [bocoup/coral-ask-election-2016#2]
We need a base react scaffold w/ a build process, hot reloading, linting, the usual. Should we just use `create-react-app`?

**Comment by vlandham** [comment]
+1 - in my experience `create-react-app` is the fastest easiest approach right now. You have something to work from in minutes. 

Just used it with a tiny project: https://github.com/vlandham/text-art without any issues.

**Comment by kadamwhite** [comment]
Didn't make a PR for this, but closing this issue as resolved by the latest master
