### ISSUE TITLE
Webpack warning on Tabletop library

### ISSUE THREAD

**Issue by kadamwhite** [bocoup/coral-ask-election-2016#26]
Including tabletop triggers this warning:

```
Warning in ./~/tabletop/src/tabletop.js
Critical dependencies:
7:18-43 the request of a dependency is an expression
 @ ./~/tabletop/src/tabletop.js 7:18-43
```

Background on that error: https://github.com/webpack/webpack/issues/196

Going to revisit this after app is fully working to determine if build needs to be somehow optimized, that thread makes it sound like we may be bundling code unnecessarily due to this issue.

**Comment by pbeshai** [comment]
Seems because it has a dynamic require in tabletop: https://github.com/jsoma/tabletop/issues/116 

> `var request = require('request'.trim());`

**Comment by kadamwhite** [comment]
This seems ignorable, the built file size is not too big so even if this is somehow causing some pruning to fail within Webpack it doesn't seem to be worrisome.
