### ISSUE TITLE
Can we reliably render a pack layout with emoji?

### ISSUE THREAD

**Issue by iros** [bocoup/coral-ask-election-2016#3]

**Comment by iros** [comment]
Maybe?

See `emoji-pack-test.html` under `experiments`.

There is an issue though. The Pack layout attaches `x`, `y` and `r` attributes to the child nodes of our tree which we can use to render the emoji, but we need to find a reliable mapping between the provided `r` value and font size. It's not likely there is a single value that will work for all emoji fonts... for example, in OSX, the layout looks like this:

![image](https://cloud.githubusercontent.com/assets/18690/19463048/ff39aad6-94be-11e6-98e8-b8a5b6e7e3ca.png)

But on android it is clearly off with the same parameters:

![image](https://cloud.githubusercontent.com/assets/18690/19463057/0e045afc-94bf-11e6-92f0-e6221b93d085.png)

This also completely fails on iOS. No idea why...!

![image](https://cloud.githubusercontent.com/assets/18690/19463070/2d8f7c12-94bf-11e6-80c5-393af6762ae0.png)

This needs some further investigation, clearly. At least we know how to use d3 for this.

**Comment by kadamwhite** [comment]
Closing this out as resolved, thanks so much for figuring this one out @iros !
