### ISSUE TITLE
Clicking on bubble chart emoji sometimes pulls the wrong letter

### ISSUE THREAD

**Issue by iros** [bocoup/coral-ask-election-2016#54]
![emojigrid-wrongletter](https://cloud.githubusercontent.com/assets/18690/19863157/87cf7e02-9f69-11e6-962f-80834527dc2d.gif)

**Comment by iros** [comment]
Ignore the styling bug, that's some weird gif artifact.

**Comment by kadamwhite** [comment]
Will be addressed by #58

**Comment by kadamwhite** [comment]
Closed in #58
