### ISSUE TITLE
Order Filter by Topic issues by % of responses

### ISSUE THREAD

**Issue by gjbarber** [bocoup/coral-ask-election-2016#66]
Request from The Washington Post graphics team:

On the Filter by Topic section, Please order the topics by percentage of responses, with the top vote-getter at the top of the list and the lowest vote-getter at the bottom of the list. 

Reason: it'll make the results more easy for users to compare.

**Comment by kadamwhite** [comment]
Taking a crack at this before I get pulled away later in the day!
