### ISSUE TITLE
Make text for the letter and the issue labels in the data viz editable

### ISSUE THREAD

**Issue by gjbarber** [bocoup/coral-ask-election-2016#71]
Text with corrected spelling and capitalization is available in the Google spreadsheet here: https://docs.google.com/spreadsheets/d/18yAMk_ydGpPLHTZPrLox7oplvgc-4aswu1arO_IHY9I/edit#gid=904229865

**Comment by iros** [comment]
@gjbarber For the issues question, those labels need to be updated in the Ask form, not in the interactive.

I will work with the template, though probably change how we specify the blanks slightly.
