### ISSUE TITLE
Remove gray bars on top of emoji graph in topics data viz section

### ISSUE THREAD

**Issue by gjbarber** [bocoup/coral-ask-election-2016#77]
Request from Washington Post Graphics team: 

The gray bars on top of the emoji graph in the topic section aren't large enough to show differences in size. The percentages below are effective enough. Can the gray bars be removed?

<img width="401" alt="20161102-emoji" src="https://cloud.githubusercontent.com/assets/14944403/19931127/cb250e5a-a0e1-11e6-9b45-f3c1fd22bdf1.png">

**Comment by kadamwhite** [comment]
@iros leaving this one to you

**Comment by iros** [comment]
Ok, though I quite like them.

**Comment by kadamwhite** [comment]
@gjbarber It's worth noting that they will show difference in size, if there's a difference. The sample above has equal values for all responses. The delta won't be great, but it's definitely possible that relationships between the bars will be visibly evident depending on the data

**Comment by vlandham** [comment]
can be disabled if need be using a flag now from #110 . 
another reason to keep them - they also provide a solid indication as to which emoji is selected, and highlight feedback. 

![barrs](https://cloud.githubusercontent.com/assets/9369/19947077/c04f1490-a103-11e6-98ca-1dd5a46fab11.gif)

Styling now has a bit of rounded corners 
![highlight](https://cloud.githubusercontent.com/assets/9369/19947101/d3b9a356-a103-11e6-8e90-7377c7f208b0.gif)
