### ISSUE TITLE
Generic id may cause integration edge case issues

### ISSUE THREAD

**Issue by jde** [bocoup/coral-ask-election-2016#84]
The script embed locks onto a div with id main:

```
<div id="root"></div><script type="text/javascript" src="./static/js/main.76efbf97.js"></script>
```

Many sites will have an element id="root". If so, it is likely that this interactive will take over the page in an unexpected way.

**Comment by kadamwhite** [comment]
Noted; this won't be an issue if it's iframe'd but that's an easy fix so we may as well do it
