### ISSUE TITLE
Form UI issues - icons too big, form jumps around

### ISSUE THREAD

**Issue by kgardnr** [bocoup/coral-ask-election-2016#85]
Steps to reproduce:
1. Go here: https://s3-us-west-2.amazonaws.com/ask-stg/build/index.html
2. Click "Tell the..." to see the form
3. Icons are oversized
4. Entering information into the form causes page and form fields to jump around (try hitting the American Flag, and entering your Name or Location)

**Comment by kadamwhite** [comment]
Looking at this now

**Comment by kadamwhite** [comment]
Learned that this is not the #1 priority so pulling off it for now

**Comment by kadamwhite** [comment]
Unable to reproduce on our own AWS instance http://elections.bocoup.com.s3-website-us-east-1.amazonaws.com/ask-stg/build/index.html
