### ISSUE TITLE
Update all paths to use the base path from config

### ISSUE THREAD

**Issue by jde** [bocoup/coral-ask-election-2016#87]
My suggestion to use relative paths wasn't sound. This works when hitting the index file directly on the S3 bucket. When embedding, however, relative paths resolve to the embedded site, not the bucket.

We will be putting the build into a folder called 'coral-ask-election-2016' inside the same place the json files are installed.

Update all paths to use the following base path: 

```
jsonURI + "coral-ask-election-2016/"
```

<img width="1429" alt="screenshot 2016-11-02 12 12 02" src="https://cloud.githubusercontent.com/assets/259957/19937016/080cd456-a0f6-11e6-9a42-3fdbb17d953d.png">

**Comment by kadamwhite** [comment]
@jde I actually recommend having jsonURI based on basePath, and defining that separately -- will work on this.

**Comment by kadamwhite** [comment]
@jde Can you or @jtnelson clarify the need here, I was under the impression we were deploying in an `<iframe>` which would not requite absolute URLs.

**Comment by jde** [comment]
You are correct. We have settled on only supporting iframe embeds so this is no longer necessary. Thanks!
